### PR TITLE
fix #2 - Convert style to MapCSS

### LINKED ISSUE #2: Convert style to MapCSS
Hi,
We plan to drop support for XML styles and keep only MapCSS, see https://josm.openstreetmap.de/ticket/12282

Could it be possible to convert this style to MapCSS? It should be relatively easy as the style is small.
We have a tutorial, here:
https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSTutorial

MapCSS complete reference is here:
https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation

Here's an example of conversion:
https://josm.openstreetmap.de/wiki/Styles/Lit?action=diff&version=5&old_version=3

### PR DESCRIPTION
**Pull request by don-vip**
We plan to drop support for XML styles and keep only MapCSS

### CODE REVIEW

**Comment by Klumbumbus** [comment]
color should be:

ofp_roadtype6#707070

(with the text before), so the user can change it in the josm color settings.

**Comment by don-vip** [comment]
done, thanks

**Comment by Klumbumbus** [comment]
XML support was dropped now. I moved this style to the unmaintained ones. https://josm.openstreetmap.de/wiki/StylesSource?sfp_email=&sfph_mail=&action=diff&version=32&old_version=31&sfp_email=&sfph_mail=
Revert this once this pull request is merged.

**Comment by don-vip** [comment]
clearly unmaintained, closing this PR

**Pull request closed without merging**
